### ISSUE TITLE
MQTT: username/password support

### ISSUE THREAD

**Issue by jipp** [ntruchsess/fhem-mirror#33]
Hi

is it possible to add username/password support to the MQTT module of fhem?
a patch is already existing, but will be overwritten when doing it the manual way.

https://forum.fhem.de/index.php/topic,32528.msg265018.html#msg265018

thanks a lot
Jipp

**Comment by lefty01** [comment]
I submitted a pull-request for this issue. 
https://github.com/ntruchsess/fhem-mirror/pull/34

**Comment by ntruchsess** [comment]
I close this issue as outdated. This is just an old mirror of fhem-svn that has not been updated since long time. FHEM-code is actually maintained at https://svn.fhem.de/
