### ISSUE TITLE
Enhancement Request: periodic connection check

### ISSUE THREAD

**Issue by hjgode** [ntruchsess/fhem-mirror#36]
Hallo

da, zumindest unter Linux, die Keep_Alive Funktionalität einen 'nicht verbundenes' MySensos Gateway im Extremfall erst nach zwei Stunden bemerken würde, schlage ich folgende Änderungen vor:

1. PASSIV: Im Timer() sub ein Readingsupdate. Dann kann man sehen, wann der Gateway zuletzt was empfangen hat. Über entsprechenden notify etc. kann man das in FHEM dann für eine 'Disconnect'-Abfrage auswerten.
2. AKTIV: Eine periodische Nachrict an den Gateway senden, um festzustellen ob er nocht 'lebt', zB die Version abfragen.

Beide Lösungen sind im folgen diff enthalten:

	--- 00_MYSENSORS.pm.org	2017-01-04 19:26:36.437086228 +0100
	+++ 00_MYSENSORS.pm	2017-01-04 07:44:12.811919078 +0100
	@@ -19,7 +19,7 @@
	 #     You should have received a copy of the GNU General Public License
	 #     along with fhem.  If not, see <http://www.gnu.org/licenses/>.
	 #
	-# $Id$
	+# $Id: 00_MYSENSORS.pm 9341 2015-10-02 14:55:54Z ntruchsess $
	 #
	 ##############################################
 
	@@ -218,6 +218,19 @@
	   return undef;
	 }
 
	+# GetConnectStatus
	+sub GetConnectStatus($){
	+	my ($hash) = @_;
	+	my $name = $hash->{NAME};
	+	Log3 $name, 4, "MySensors: GetConnectStatus called ...";
	+    
	+	#query version from gateway 
	+    sendMessage($hash, radioId => 0, childId => 0, cmd => C_INTERNAL, ack => 0, subType => I_VERSION, payload => '');
	+ 
	+	# neuen Timer starten in einem konfigurierten Interval.
	+	InternalTimer(gettimeofday()+300, "MYSENSORS::GetConnectStatus", $hash);
	+}
	+
	 sub Timer($) {
	   my $hash = shift;
	   my $now = time;
	@@ -247,6 +260,8 @@
	   Log3 ($name, 5, "MYSENSORS/RAW: $data/$buf");
	   $data .= $buf;
 
	+  readingsSingleUpdate($hash,"lastRead","$buf",1);
	+
	   while ($data =~ m/\n/) {
		 my $txt;
		 ($txt,$data) = split("\n", $data, 2);
	@@ -348,6 +363,8 @@
			   my $client = shift;
			   MYSENSORS::DEVICE::onGatewayStarted($client);
			 });
	+		#start connect watch thread, interval 500
	+		InternalTimer(gettimeofday()+300, "MYSENSORS::GetConnectStatus", $hash);
			 last;
		   };
		   $type == I_VERSION and do {

Ich würde mich freuen, wenn zumindest die zweite Lösung im Code eingebaut würde. Bei mir läuft das zur Zeit mit beiden Änderungen.

Das Problem bei Batterie-betriebenen Sensoren ist, dass Sie eventuell nur selten etwas senden. Man weiss also nie ob die noch leben oder die Verbindung zum Gateway 'tot' ist. Ist mir des öfteren passiert und meistens war die Gateway Verbindung weg. Das erste Keep_Alive Paket wird bei Linux erst nach zwei Stunden gesendet. Dies kann man aber über perl socket Optionen anpassen (eine entsprechende Änderung habe ich auch schon im FHEM Forum gepostet). Nach den zwei Stunden wird dann alle 75 Sekunden ein Keep_Alive Packet gesendet.

~Josef

**Comment by Kolbi** [comment]
Ich habe daraus mal einen PR erstellt. Getestet habe ich Anpassung bisher (!) noch nicht. Dies würde aber sicherlich das Testen für andere erleichtern.

**Comment by ntruchsess** [comment]
I close this issue as outdated. This is just an old mirror of fhem-svn that has not been updated since long time. FHEM-code is actually maintained at https://svn.fhem.de/
