### ISSUE TITLE
Support for 433Mhz (Intertechno) Radios in FRM

### ISSUE THREAD

**Issue by ntruchsess** [ntruchsess/fhem-mirror#8]
http://forum.fhem.de/index.php/topic,10744.msg110669.html#msg110669

**Comment by git-developer** [comment]
see also:
https://github.com/git-developer/RCSwitchFirmata
https://github.com/firmata/ConfigurableFirmata/issues/68
https://github.com/ntruchsess/perl-firmata/issues/26

**Comment by ntruchsess** [comment]
outdated
